version: '3'
services:
  backend:
    build: .
    ports:
      - '3001:3001'
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pedido_cirurgico_a3data
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - '3307:3306'
